\c postgres;

DROP DATABASE IF EXISTS spotitube;
CREATE DATABASE spotitube;

\c spotitube;

CREATE TABLE IF NOT EXISTS tracks (
    ID SERIAL,
    TITLE CHAR(50),
    PERFORMER CHAR(50),
    DURATION INT,
    ALBUM CHAR(50),
    PLAYCOUNT INT,
    PUBLICATION_DATE DATE,
    DESCRIPTION CHAR(100),
    OFFLINE_AVAILABLE BOOLEAN,
    CONSTRAINT PK_tracks_id PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS users (
    ID SERIAL,
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(50),
    TOKEN varchar(255),
    CONSTRAINT PK_users_id PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS playlists (
    ID SERIAL,
    NAME CHAR(50),
    OWNER INT,
    CONSTRAINT PK_playlists_id PRIMARY KEY (ID),
    CONSTRAINT FK_playlistOwner_userId FOREIGN KEY (OWNER) REFERENCES users(ID)
);

CREATE TABLE IF NOT EXISTS tracksInPlaylist(
   TRACK_ID INT NOT NULL,
   PLAYLIST_ID INT NOT NULL,
   CONSTRAINT FK_playlist FOREIGN KEY (PLAYLIST_ID) REFERENCES playlists(ID),
   CONSTRAINT FK_track FOREIGN KEY (TRACK_ID) REFERENCES tracks(ID),
   CONSTRAINT UN_index UNIQUE (TRACK_ID, PLAYLIST_ID)
);

